In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
tf.__version__

'2.7.0'

In [3]:
hello=tf.constant("Hello")

In [4]:
world=tf.constant("world")

In [5]:
type(world)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result= sess.run(hello+world)

In [8]:
print(result)

b'Helloworld'


In [9]:
a= tf.constant(10)

In [10]:
b=tf.constant(20)

In [11]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result= sess.run(a+b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [18]:
fillmat=tf.fill((4,4),10)

In [20]:
my_ones= tf.ones((4,4))

In [21]:
my_zeroes= tf.zeros((4,4))

In [22]:
my_randn = tf.random_normal((4,4),mean=0, stddev=1)

In [23]:
my_randu = tf.random_uniform((4,4),minval=0,maxval=1)

In [27]:
my_ops = [const,fillmat,my_ones,my_zeroes,my_randn,my_randu]

In [28]:
sess=tf.InteractiveSession()

C:\Users\Ultimatrix\anaconda3\lib\site-packages\tensorflow\python\client\session.py:1771: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [29]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-1.2186135   1.4531053   0.05177876 -0.86705685]
 [-0.50914145 -0.07769264 -0.68545425  2.3048575 ]
 [-2.04344     0.44241852  2.26474    -0.09883451]
 [ 0.80259067 -0.3929622   0.4316467   0.60948515]]


[[0.14268577 0.42826676 0.74179494 0.66052675]
 [0.31040835 0.10415304 0.5696515  0.8447492 ]
 [0.6669853  0.4131292  0.9374788  0.25566304]
 [0.7558943  0.90150714 0.5425931  0.8192588 ]]




In [30]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[ 1.5072372  -0.14228092 -0.4449344  -1.8415581 ]
 [-0.9566722   0.15947637  0.13165045 -0.8790255 ]
 [-0.3506743   0.27527088  0.11499887  0.8362149 ]
 [ 0.45303088 -2.3024235   0.6620392  -0.79074645]]


[[0.9067042  0.6530957  0.33617234 0.3745631 ]
 [0.93873894 0.7978871  0.37975764 0.52020276]
 [0.6444254  0.43766904 0.50456834 0.98101056]
 [0.43152916 0.11598754 0.03234696 0.94863427]]




In [31]:
## Matrix Multiplication

In [32]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([[10],[100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a,b)

In [40]:
result.eval()
#or
#sess.run(result) 

array([[210],
       [430]])